version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:latest
    environment:
      - SOURCE_BRANCH: master
    filters:
      branches:
        only: master
    steps:
      - deploy:
          name: Deploy to Heroku
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $SOURCE_BRANCH
            fi

