version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:latest
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-

      - run:
          name: Build Application
          command: yarn build

      - add_ssh_keys:
          fingerprints:
            - "73:ba:91:9a:31:bb:37:d7:ca:cc:ae:e2:ad:80:44:9a"
      - run:
          name: Install and configure dependencies
          command: npm install -g --silent gh-pages@2.0.1

      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist build/

