version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:latest
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9b:31:1a:df:0e:68:d6:47:16:31:14:d9:48:13:9b:36"
      - checkout
      - restore_cache:
          keys:
            - dependencies-
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-


      - run:
          name: Run deploy scripts
          command: ../scripts/deploy.sh
