version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:latest
    environment:
      - SOURCE_BRANCH: master
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-

      - add_ssh_keys:
          fingerprints:
            - "73:ba:91:9a:31:bb:37:d7:ca:cc:ae:e2:ad:80:44:9a"


      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              yarn build

              cp -r build/. docs/.

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $SOURCE_BRANCH
            fi

